#!/bin/bash
 #*************************************************
 # Start the constructor
 #*************************************************
source ~/.cache/code-gathering/common/constructor
depends package github

 #*************************************************
 # Install and configure github
 #*************************************************
installGithub() {
	#TODO install github
	setupGithub
}
 #*************************************************
 # Setup Code Gathering Projects
 #*************************************************
 setupCodeGathering() {
 	cd ~
 	mkdir development
 	cd development
 	mkdir github
 	cd github

 	echo "Fork my project!"
 	sleep 2;
 	google-chrome "https://github.com/rvaronos/code-gathering"
 	pause;

 	git clone git@github.com:$username/code-gathering.git
 	cd code-gathering
 	git remote add upstream git://github.com/rvaronos/code-gathering.git
 	git fetch upstream
 }
 setupSublime() {

 	npm install -g compiler-js
 	cd ~/"Library/Application Support/Sublime Text 2/Packages/"
 }

exitOptions(){
echo "To start again, press Relaunch"
sleep 1
clear
exit
}
titles=(
"Install Packages"
"Install and configure github"
"Code Gathering project bundle configuration"
"Exit"
)
callbacks=(
installPackages
installGithub
setupCodeGathering
exitOptions
)
options titles[@] callbacks[@] '${callback}'
