#!/bin/bash

 #*************************************************
 # Start the constructor
 #*************************************************

source constructor

 #*************************************************
 # Install and configure github
 #*************************************************

installGithub() {

	#TODO install github
	include tools github 
	setupGithub
}

 #*************************************************
 # Install packages 
 #*************************************************

installPackages() {

info "Getting packages to install"
get ${projectURL} packages

 while read line
 do

 		if [ '$line' = *\[* ]
 		then
 	echo $line
 fi

 done < packages

}

 #*************************************************
 # Setup Code Gathering Projects
 #*************************************************

 setupProjects() {

 	cd ~
 	mkdir development
 	cd development
 	mkdir github
 	cd github

 	echo "Fork my project!"
 	sleep 2;
 	google-chrome "https://github.com/rvaronos/code-gathering"
 	pause;

 	git clone git@github.com:$username/code-gathering.git
 	cd code-gathering
 	git remote add upstream git://github.com/rvaronos/code-gathering.git
 	git fetch upstream
 }
 setupSublime() {

 	npm install -g compiler-js
 	cd ~/"Library/Application Support/Sublime Text 2/Packages/"
 }

printOptions "Install Packages" "Setup your Github account"
option installPackages installGithub
