#!/bin/bash

#****************************************************
# Package list for automatically checking and
# installing applications to a debian distribution
#****************************************************

packageKeys=(
"https://dl-ssl.google.com/linux/linux_signing_key.pub"
)

packageDebs=(
# Sublime Text 2 - IDE
"webupd8team;http://ppa.launchpad.net/webupd8team/sublime-text-2/ubuntu precise main"
# NodeJS
"sid;ftp.us.debian.org/debian/ sid main",
# Google Chrome browser
"google-chrome;dl.google.com/linux/chrome/deb/ stable main",
"geogebra;download.opensuse.org/repositories/home:heimdall78/xUbuntu_11.10/ /"
)

packages=(
# Development
nodejs,
npm,
sublime-text-2-beta,
git,
# Internet Browsers
google-chrome-stable,
firefox,
opera,
# Database
mysql-server,
phpmyadmin,
# TODO: Add Screencasting tools ffmpeg vp8 encoding 
# Helper Tools
geogebra
)
