#!/bin/bash

base=https://raw.github.com/rvaronos/code-gathering/master/terminal
project=$1

#**********************************************************************
# Start gnome terminal with the script specified running a 
#**********************************************************************

source <(wget -qO- ${base}/tools/profile)
updateProfile CodeGathering
script=$(wget -qO- ${base}/${project}/script)
gnome-terminal --tab-with-profile=CodeGathering -e $script




