#!/bin/bash

setupGithub() {

ask "Do you have a github account?"

if $reply
then
info "Awesome! No need to register"
sleep 1
else
google-chrome "https://github.com/signup/free"
 	step "Register an account at github.com"
 fi

 	cd ~/.ssh 

 	if [ ! -d "key_backup" ]
 		then
    # makes a subdirectory called "key_backup" in the current directory
    mkdir key_backup 
fi

     	# Copies the id_rsa and id_rsa.pub files into key_backup
     	cp id_rsa* key_backup
     	rm id_rsa*

     	readInput "Enter your email, followed by [ENTER]" 
     	email=$reply

     	generateKey(){

     		step "Press [ENTER] when asked to save the key"
 	# Creates a new ssh key using the provided email
 	ssh-keygen -t rsa -C $email

 	if [ ! -f "id_rsa" ]
 		then
     	
     	info "There was a problem. Trying again"
     	generateKey;
     fi
 }
 generateKey;

 sublime-text-2 ~/.ssh/id_rsa.pub
 step "Copy the entire text ..."
 google-chrome "https://github.com/settings/ssh"
 step "Add SSH key ..."
 info "Testing github ..."
 sleep .5;
 step "Type “yes” when prompted";
 ssh -T git@github.com
 info "Setting up your github account...";
 sleep 0.5;
 readInput "Enter First and Last name, followed by [ENTER]"
 fullname=$reply

 git config --global user.name $fullname
 git config --global user.email $email


 info "*Note* If you ever change your GitHub password, a new token will be created and will need to be updated..."
 pause;
}
restoreGithub(){
 	cd ~/.ssh 
     	# Copies the id_rsa and id_rsa.pub files into key_backup
     	cp key_backup/id_rsa* ./
ssh -T git@github.com
}

info "Added github functions"
