#!/bin/bash

#*************************************************
# Add APT source the package's list file
# ${1} Package name
# ${2} DEB line
#*************************************************

addSource(){

local sourcePath="/etc/apt/sources.list.d/${1}.list"
local debLine="deb http://${2}"

# Search for an existing source line in text file
if [ -f ${sourcePath} ] && [ $(findLine ${debLine} ${sourcePath}) != 0 ]
then
	log "\"${sourcePath}\" already contains \"${debLine}\"" 
	return
fi

addLine ${debLine} ${sourcePath}

}

#*************************************************
# Install packages 
#*************************************************

installPackages() {

info "Getting packages to install"
include packages -local

for package in $packages
do 
echo $package
done

installPackage(){
if which ${1} > /dev/null
then
   echo "${1} package already exists"
else
      sudo apt-get install ${1}
fi
}

}
