#!/bin/bash

baseURL="https://raw.github.com/rvaronos/code-gathering/master/terminal"
sep="----------------------"
iwd=${PWD}

#**********************************************************
# Get cache folder and include constructor to the source 
# TODO: When cache clears do not delete the common folder
# and the constructor script
#**********************************************************

cd ~/.cache/
mkdir -p code-gathering
cd code-gathering
mkdir -p common
cd common

if [ "${1}" == "--ncc" ] || $( ! [ -f constructor ] )
then
curl -# ${baseURL}/common/constructor > constructor
else
echo "Using cached file: constructor"
fi
source constructor

depends profile

loadProject(){
 
#****************************************************
# Get scripts from an online repository
#****************************************************

clearAllCache(){
rm -rf ~/.cache/code-gathering/*
echo "Cache cleared"
getOption
}

initProject(){

#************************************************
# List available projects
#************************************************

local titles=()
local callbacks=()
local i=0

read -r LINE_ARRAY <<< "$(curl -# ${baseURL}/projects/list)"

IFS=";" 

for x in "${LINE_ARRAY[@]}"
do

read -ra STR_ARRAY <<< "$x"
titles[${i}]="${STR_ARRAY[0]} - ${STR_ARRAY[1]}"
callbacks[${i}]=${STR_ARRAY[0]}

((i++))
done

echo "Enter project's index: "
options titles[@] callbacks[@] 'projectName=${callback}'
echo "Selected project: ${projectName}"

#************************************************************************
# Start gnome terminal with the script specified running custom Profile
#************************************************************************


checkProfile CodeGathering

mkdir -p ${projectName}
cd ${projectName}
getLocal main 
gnome-terminal --tab-with-profile=CodeGathering --command="bash main ${projectName} ${baseURL}"
}

exitOptions(){
echo "To start again, type: loadProject"
}

echo -e "${sep}\nChoose an option:\n${sep}"

local titles=(
"Initialise Project"
"Clear all cache"
"Exit"
)
local callbacks=(
initProject
clearAllCache
exitOptions
)

options titles[@] callbacks[@] '${callback}'

echo ${sep}

}
loadProject
# Go back to initial working directory
cd "${iwd}"









