#!/bin/bash

sep="----------------------"
iwd=${PWD}

initOptions(){

get(){
if [ -f $2 ]
then
echo "${2} exists.. aborting"
return
fi
curl -# ${1}/${2} > ${2}
}

clearAllCache(){
rm ~/.cache/code-gathering/*
echo "Cache cleared"
getOption
}

initProject(){

get ${base}/tools string
source string

base=https://raw.github.com/rvaronos/code-gathering/master/terminal
projects=()

while read -r line; do

local i=0

printf "\n[%1d] : %5s - %20s" ${i} ${line[0]} ${line[1]}
projects[${i}]=$(substr $line 1)

((i++))

done <<< "$(curl -# ${base}/projects)"

printf "\n\n"

echo -n "Enter project's index: "
read -s -n1 index

project=${projects[0]}
echo $project
return

# Get the cache folder ready
cd ~/.cache/
mkdir -p code-gathering
cd code-gathering

get ${base}/tools profile

#************************************************************************
# Start gnome terminal with the script specified running custom Profile
#************************************************************************

source profile

checkProfile CodeGathering
gnome-terminal --tab-with-profile=CodeGathering -e script

}

clear;

addOptions(){
local i=1
for option in "$@"
do
echo "[${i}] ${option}"
((i++))
done
}

exitOptions(){
echo "To start again, type: initOptions"
}

echo -e "${sep}\nChoose an option:\n${sep}"
addOptions "Initialise Project" "Clear all cache" "Exit"
echo ${sep}

getOption(){
read -s -n1 ans
${optionFunc[$(( $ans - 1 ))]}
}

option(){
optionFunc=(${@} getOption)
getOption
}

option initProject clearAllCache exitOptions

}
initOptions
# Go back to initial working directory
cd "${iwd}"









