#!/bin/bash

#*************************************************
# Add APT source the package's list file
# ${1} Package name
# ${2} DEB line
#*************************************************

addSource(){

local sourcePath="/etc/apt/sources.list.d/${1}.list"
local debLine="deb http://${2}"

if [ -f ${sourcePath} ]
then

# Search for an existing source line in text file

if [ $(findLine ${debLine} ${sourcePath}) = 0 ]
then
	addLine ${debLine} ${sourcePath}
else
	log "\"${sourcePath}\" already contains \"${debLine}\"" 
fi

sudo sh -c "echo \"${2}\" >> ${sourcePath}"

fi

}

#*************************************************
# Install packages 
#*************************************************

installPackages() {

info "Getting packages to install"
include packages -local

installPackage(){
if which ${1} > /dev/null
then
   echo "${1} package already exists"
then
      sudo apt-get install ${1}
   fi
fi
}

include tools string


get ${projectURL} packages



 done < packages

}
