#!/bin/bash

#*************************************************
# Add APT source the package's list file
# ${1} Package name
# ${2} DEB line
#*************************************************

addSource(){

local sourcePath="/etc/apt/sources.list.d/${1}.list"
local debLine="deb http://${2}"

if [ -f ${sourcePath} ]
then

# Search for an existing source line in text file

if [ $(findLine ${debLine} ${sourcePath}) = 0 ]
then
	addLine ${debLine} ${sourcePath}
else
	log "\"${sourcePath}\" already contains \"${debLine}\"" 
fi

sudo sh -c "echo \"${2}\" >> ${sourcePath}"

fi

}

#*************************************************
 # Install packages 
 #*************************************************

installPackages() {

local action=

include tools string

info "Getting packages to install"
get ${projectURL} packages

 while read line
 do

 		if [[ $line = *[* ]]
	
 		then

case $(between $line "[" "]") in

"key") 
    ;;
"ppa")  
    ;;
"list") 
    ;;
"package") 
   ;;
esac
 fi

 done < packages

}
