#!/bin/bash

indexOf(){
return | awk -v string="$1" -v search="$2" 'BEGIN{print index(string,search)}'
}
substr(){
return | awk -v s="$1" -v a="$2" 'BEGIN{print substr(s,a)}'
}
substrl(){
return | awk -v s="$1" -v a="$2" -v b="$3" 'BEGIN{print substr(s,a,b)}'
}
replace(){
return | awk -v  -v regex="$2" replacement="$3" target="$3" 'BEGIN{print sub(regex,replacement,target)}'
}
